# Generated by Django 6.1 on 2026-09-22 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_logo_alter_business_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='verified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
