# Generated by Django 6.1 on 2026-09-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_verification_defaults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='city',
            new_name='town_or_city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='country',
        ),
        migrations.RemoveField(
            model_name='business',
            name='province',
        ),
    ]
