# Generated by Django 6.1 on 2026-09-26 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_rename_city_business_town_or_city_and_more'),
        ('categories', '0002_remove_category_image'),
        ('products', '0011_seed_product_classification_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store, market, or outlet name.', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('town_or_city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Opening hours, stock notes, or other details.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_locations', to='businesses.business')),
            ],
            options={
                'ordering': ['town_or_city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('company_profile', 'Company profile'), ('new_product', 'New product'), ('product_update', 'Product update'), ('retail_location', 'Retail location')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('business_type', models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('farmer', 'Farmer'), ('producer', 'Producer'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('service', 'Service'), ('brand', 'Brand'), ('other', 'Other')], max_length=30)),
                ('company_description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('town_or_city', models.CharField(blank=True, max_length=100)),
                ('logo_upload', models.ImageField(blank=True, null=True, upload_to='submissions/logos/')),
                ('product_name', models.CharField(blank=True, max_length=250)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('product_description', models.TextField(blank=True)),
                ('origin_type', models.CharField(blank=True, max_length=30)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('size_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_unit', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_image_upload', models.ImageField(blank=True, null=True, upload_to='submissions/products/')),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_address', models.TextField(blank=True)),
                ('location_town_or_city', models.CharField(blank=True, max_length=100)),
                ('location_phone', models.CharField(blank=True, max_length=50)),
                ('location_notes', models.TextField(blank=True)),
                ('submitter_notes', models.TextField(blank=True, help_text='Anything reviewers should know.')),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='businesses.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manufacturer_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_submissions', to=settings.AUTH_USER_MODEL)),
                ('retail_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='businesses.retaillocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
