# Generated by Django 6.1 on 2026-09-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_retail_location_and_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
