# Generated by Django 6.1 on 2026-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_backfill_data_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
