# Generated by Django 6.1 on 2026-10-07 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_verified_at_no_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='confirmed_owner',
            field=models.ForeignKey(blank=True, help_text='User whose ownership staff confirmed. Only a confirmed owner can mark listings as Verified manufacturer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
