# Generated by Django 6.1 on 2026-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_business_owner_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to take this listing and its products offline (pages return 404). To record that the company has stopped trading, set the verification level to Discontinued instead.'),
        ),
    ]
