# Generated by Django 6.1 on 2026-10-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_business_is_active_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retaillocation',
            name='business',
        ),
        migrations.DeleteModel(
            name='ManufacturerSubmission',
        ),
        migrations.DeleteModel(
            name='RetailLocation',
        ),
    ]
