# Generated by Django 6.1 on 2026-10-08 23:38

from django.db import migrations, models

LEGACY_TYPE_MAP = {
    "farmer": "manufacturer",
    "producer": "manufacturer",
    "brand": "manufacturer",
    "service": "service_provider",
    "retailer": "other",
    "wholesaler": "other",
}


def remap_business_types(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    for old, new in LEGACY_TYPE_MAP.items():
        Business.objects.filter(business_type=old).update(business_type=new)


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_drop_submissions_and_retail_locations'),
    ]

    operations = [
        migrations.RunPython(remap_business_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('service_provider', 'Service Provider'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
