# Generated by Django 6.1 on 2026-10-09 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

LEVEL_MAP = {
    "verified_manufacturer": "simudza_verified",
    "simudza_checked": "simudza_verified",
    "verified_source": "source_verified",
}


def split_levels_and_lifecycle(apps, schema_editor):
    """Discontinued becomes a lifecycle status; its old level is unknown, so unverified."""
    Business = apps.get_model("businesses", "Business")
    Business.objects.filter(verification_level="discontinued").update(
        lifecycle_status="discontinued",
        verification_level="unverified",
    )
    for old, new in LEVEL_MAP.items():
        Business.objects.filter(verification_level=old).update(verification_level=new)


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_business_type_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name': 'business', 'verbose_name_plural': 'businesses'},
        ),
        migrations.AddField(
            model_name='business',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued / withdrawn')], db_index=True, default='active', help_text='Discontinued keeps the page online with a notice but removes the business and its products from search.', max_length=20),
        ),
        migrations.RunPython(split_levels_and_lifecycle, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='business',
            name='confirmed_owner',
            field=models.ForeignKey(blank=True, help_text="User whose ownership staff confirmed. Only a confirmed owner's confirmations mark listings as Simudza Verified.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to take this listing and its products offline (pages return 404). To record that the company has stopped trading, set the lifecycle status to Discontinued instead.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='verification_level',
            field=models.CharField(choices=[('simudza_verified', 'Simudza Verified'), ('source_verified', 'Information source checked'), ('community_reported', 'Community reported — not verified by Simudza'), ('unverified', 'Not yet verified')], db_index=True, default='unverified', max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='verification_reference',
            field=models.CharField(blank=True, help_text='Source name or URL when level is Information source checked.', max_length=300),
        ),
    ]
