# Generated by Django 6.1 on 2026-10-09 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

OLD_TO_NEW = {
    "factory_tour": "business_tour",
    "review": "testimonial",
    "demonstration": "other",
}


def remap_kinds(apps, schema_editor):
    BusinessVideo = apps.get_model("businesses", "BusinessVideo")
    for old, new in OLD_TO_NEW.items():
        BusinessVideo.objects.filter(kind=old).update(kind=new)


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_drop_invalid_contact_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='confirmed_owner',
            field=models.ForeignKey(blank=True, help_text="User whose ownership staff confirmed. A confirmed owner's edits count as Information source checked; only superusers grant Simudza Verified.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessvideo',
            name='kind',
            field=models.CharField(choices=[('business_tour', 'Factory or business tour'), ('manufacturing', 'Manufacturing process'), ('project_portfolio', 'Project portfolio'), ('interview', 'Producer or business interview'), ('capacity_supply', 'Products, capacity and supply'), ('testimonial', 'Customer testimonial'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.RunPython(remap_kinds, migrations.RunPython.noop),
    ]
