# Generated by Django 6.1 on 2026-10-03 08:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_cart_tokens(apps, schema_editor):
    import uuid as uuid_lib

    Cart = apps.get_model("marketplace", "Cart")
    ProductVariant = apps.get_model("products", "ProductVariant")
    CartItem = apps.get_model("marketplace", "CartItem")

    for cart in Cart.objects.all().iterator():
        if not cart.token:
            cart.token = uuid_lib.uuid4()
        if not cart.last_activity_at:
            cart.last_activity_at = cart.updated_at
        cart.save(update_fields=["token", "last_activity_at"])

    for item in CartItem.objects.all().iterator():
        item.added_at = item.cart.created_at
        if item.price_snapshot is None and item.variant_id:
            variant = ProductVariant.objects.filter(pk=item.variant_id).first()
            if variant and variant.price is not None:
                item.price_snapshot = variant.price
        item.save(update_fields=["added_at", "price_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_variant_lines'),
        ('products', '0025_rename_product_quality_gin_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('added', 'Added'), ('quantity_changed', 'Quantity changed'), ('removed', 'Removed'), ('merged', 'Merged'), ('converted', 'Converted')], max_length=32)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_delta', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-last_activity_at']},
        ),
        migrations.AddField(
            model_name='cart',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='marketplace.cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(assign_cart_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('converted_at__isnull', True), ('merged_into__isnull', True), ('user__isnull', False)), fields=('user',), name='unique_open_cart_per_user'),
        ),
        migrations.AddField(
            model_name='cartevent',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.cart'),
        ),
        migrations.AddField(
            model_name='cartevent',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_events', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='cartevent',
            index=models.Index(fields=['kind', 'created_at'], name='marketplace_kind_52c7c6_idx'),
        ),
    ]
