# Generated by Django 6.1 on 2026-10-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_variant'),
        ('products', '0023_productvariant_productvariant_price_not_negative_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='inventory_reserved_not_above_quantity'),
        ),
    ]
