# Generated by Django 6.1 on 2026-10-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
