# Generated by Django 6.1 on 2026-10-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
