# Generated by Django 6.1 on 2026-09-30 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_search_field_indexes'),
        ('products', '0015_alter_productclassificationpage_body'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessreview',
            name='unique_user_business_review',
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_user_product_review',
        ),
        migrations.AddField(
            model_name='businessreview',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businessreview',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businessreview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessreview',
            name='reason',
            field=models.CharField(blank=True, choices=[('product_discontinued', 'Product discontinued'), ('not_made_in_zimbabwe', 'No longer made in Zimbabwe'), ('business_closed', 'Business closed'), ('price_incorrect', 'Price incorrect'), ('product_unavailable', 'Product unavailable'), ('wrong_contact_details', 'Wrong contact details'), ('duplicate_listing', 'Duplicate listing')], max_length=40),
        ),
        migrations.AddField(
            model_name='businessreview',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessreview',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='productreview',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='productreview',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productreview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reason',
            field=models.CharField(blank=True, choices=[('product_discontinued', 'Product discontinued'), ('not_made_in_zimbabwe', 'No longer made in Zimbabwe'), ('business_closed', 'Business closed'), ('price_incorrect', 'Price incorrect'), ('product_unavailable', 'Product unavailable'), ('wrong_contact_details', 'Wrong contact details'), ('duplicate_listing', 'Duplicate listing')], max_length=40),
        ),
        migrations.AddField(
            model_name='productreview',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='businessreview',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', ''), ('user__isnull', False)), fields=('user', 'business'), name='unique_user_business_review'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', ''), ('user__isnull', False)), fields=('user', 'product'), name='unique_user_product_review'),
        ),
    ]
