# Generated by Django 6.1 on 2026-09-30 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(max_length=300)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], db_index=True, max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('field_label', models.CharField(blank=True, max_length=200)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by_repr', models.CharField(blank=True, max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('dashboard', 'Dashboard'), ('submission', 'Submission'), ('import', 'Import'), ('system', 'System'), ('web', 'Web')], db_index=True, default='web', max_length=20)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'change log entry',
                'verbose_name_plural': 'change log',
                'ordering': ['-changed_at', '-pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-changed_at'], name='history_changelog_obj_time')],
            },
        ),
    ]
