# Generated by Django 6.1 on 2026-09-29 22:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Proudly Zimbabwean', 'help_text': 'Short label shown above the heading.', 'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Discover and buy products made in Zimbabwe', 'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Simudza connects you with local businesses and the products they make, grow, package and assemble — so every purchase helps build Zimbabwe.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'The button is hidden when the label or link is empty.', 'max_length': 60, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page to link to. Takes priority over the URL below.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'A path such as "/directory/" or a full URL.', 'label': 'URL', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('page', 4), ('link_url', 5)]], {'default': {'label': 'Explore products', 'link_url': '/directory/', 'page': None}, 'label': 'Primary button'}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('page', 4), ('link_url', 5)]], {'default': {'label': 'Browse businesses', 'link_url': '/businesses/', 'page': None}, 'label': 'Secondary button'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional. Without an image the hero is centred.', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('right', 'Right'), ('left', 'Left')], 'help_text': 'Image side on large screens. On mobile it sits below the text.'}), 10: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('subheading', 2), ('primary_cta', 6), ('secondary_cta', 7), ('image', 8), ('image_position', 9)]], {})}),
        ),
    ]
