# Generated by Django 6.1 on 2026-10-01 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0010_videos'),
        ('products', '0022_videos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('business', 'Business'), ('product', 'Product')], db_index=True, max_length=20)),
                ('score', models.PositiveSmallIntegerField(help_text='Detection confidence, 0–100.')),
                ('reasons', models.JSONField(blank=True, default=list, help_text='Signals that matched, e.g. similar name or same barcode.')),
                ('status', models.CharField(choices=[('open', 'Needs review'), ('duplicate', 'Confirmed duplicate'), ('distinct', 'Not a duplicate')], db_index=True, default='open', help_text='Reviewing never changes or deletes either listing. Archive or edit the extra listing yourself if this is a duplicate.', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_signal_codes', models.JSONField(blank=True, default=list, help_text='Signals present at review time; new strong signals reopen the flag.')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='businesses.business')),
                ('business_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='businesses.business')),
                ('product_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('product_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'possible duplicate',
                'verbose_name_plural': 'possible duplicates',
                'ordering': ['-score', '-last_detected_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('business_a__isnull', False), ('business_a__lt', models.F('business_b')), ('business_b__isnull', False), ('kind', 'business'), ('product_a__isnull', True), ('product_b__isnull', True)), models.Q(('business_a__isnull', True), ('business_b__isnull', True), ('kind', 'product'), ('product_a__isnull', False), ('product_a__lt', models.F('product_b')), ('product_b__isnull', False)), _connector='OR'), name='duplicateflag_ordered_pair_matches_kind'), models.UniqueConstraint(condition=models.Q(('kind', 'business')), fields=('business_a', 'business_b'), name='unique_duplicateflag_business_pair'), models.UniqueConstraint(condition=models.Q(('kind', 'product')), fields=('product_a', 'product_b'), name='unique_duplicateflag_product_pair')],
            },
        ),
    ]
