# Generated by Django 6.1 on 2026-09-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorylisting',
            options={'ordering': ['-featured', 'product__name'], 'verbose_name_plural': 'directory listings'},
        ),
        migrations.RemoveField(
            model_name='directorylisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='directorylisting',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='directorylisting',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='directorylisting',
            name='status',
        ),
        migrations.RemoveField(
            model_name='directorylisting',
            name='title',
        ),
        migrations.AddField(
            model_name='directorylisting',
            name='show_in_directory',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this product from the public directory.'),
        ),
    ]
