# Generated by Django 6.1 on 2026-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origin_type',
            field=models.CharField(choices=[('made_in_zimbabwe', 'Made in Zimbabwe'), ('grown_in_zimbabwe', 'Grown in Zimbabwe'), ('packaged_in_zimbabwe', 'Packaged in Zimbabwe'), ('branded_in_zimbabwe', 'Branded in Zimbabwe'), ('support_image_of_zimbabwe', 'Support Image of Zimbabwe'), ('other', 'Other')], default='made_in_zimbabwe', max_length=30),
        ),
    ]
