# Generated by Django 6.1 on 2026-09-25 23:22

from django.db import migrations, models


def remap_removed_origin_types(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(origin_type="branded_in_zimbabwe").update(
        origin_type="supports_zimbabwe",
    )
    Product.objects.filter(origin_type="support_image_of_zimbabwe").update(
        origin_type="supports_zimbabwe",
    )


def reverse_remap_origin_types(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(origin_type="supports_zimbabwe").update(
        origin_type="support_image_of_zimbabwe",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_verification_defaults"),
    ]

    operations = [
        migrations.RunPython(
            remap_removed_origin_types,
            reverse_remap_origin_types,
        ),
        migrations.AlterField(
            model_name="product",
            name="origin_type",
            field=models.CharField(
                choices=[
                    ("made_in_zimbabwe", "Made in Zimbabwe"),
                    ("grown_in_zimbabwe", "Grown in Zimbabwe"),
                    ("packaged_in_zimbabwe", "Packaged in Zimbabwe"),
                    ("assembled_in_zimbabwe", "Assembled in Zimbabwe"),
                    ("supports_zimbabwe", "Supports Zimbabwe"),
                    ("other", "Other"),
                ],
                default="made_in_zimbabwe",
                help_text=(
                    "Made in Zimbabwe: substantially manufactured/processed in "
                    "Zimbabwe (e.g. a biscuit manufactured and finished in "
                    "Zimbabwe). Grown in Zimbabwe: the primary agricultural/raw "
                    "material is produced in Zimbabwe (e.g. cotton, tobacco, "
                    "maize, tomatoes). Packaged in Zimbabwe: produced elsewhere, "
                    "but final packaging is done in Zimbabwe (e.g. imported "
                    "product bulk-packed/labeled locally). Assembled in "
                    "Zimbabwe: components made elsewhere, final product "
                    "assembled in Zimbabwe. Supports Zimbabwe: does not meet "
                    "stronger production criteria, but has a documented "
                    "Zimbabwean economic/business connection. Other: does not "
                    "fit the defined classifications."
                ),
                max_length=30,
            ),
        ),
    ]
