# Generated by Django 6.1 on 2026-09-25 23:41

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_update_origin_types'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClassificationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional intro shown above the classification guide.')),
            ],
            options={
                'verbose_name': 'Product classification page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_type',
            field=models.CharField(choices=[('made_in_zimbabwe', 'Made in Zimbabwe'), ('grown_in_zimbabwe', 'Grown in Zimbabwe'), ('packaged_in_zimbabwe', 'Packaged in Zimbabwe'), ('assembled_in_zimbabwe', 'Assembled in Zimbabwe'), ('supports_zimbabwe', 'Supports Zimbabwe'), ('other', 'Other')], default='made_in_zimbabwe', help_text='Made in Zimbabwe: substantially manufactured/processed in Zimbabwe (e.g. a biscuit manufactured and finished in Zimbabwe). Grown in Zimbabwe: the primary agricultural or plant-based raw material is produced in Zimbabwe (e.g. cotton, maize, tobacco, tea). Packaged in Zimbabwe: manufactured/produced elsewhere, but the final packaging operation occurs in Zimbabwe. Assembled in Zimbabwe: components manufactured elsewhere, final assembly happens in Zimbabwe. Supports Zimbabwe: does not meet stronger production criteria, but has a documented Zimbabwean economic/business connection. Other: does not fit the defined classifications.', max_length=30),
        ),
    ]
