# Generated by Django 6.1 on 2026-09-26 03:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_restore_search_field_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclassificationpage',
            name='body',
            field=wagtail.fields.StreamField([('important_note', 1), ('classification', 11)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'Shown as a highlighted note near the top of the page.'}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classification name, e.g. "Made in Zimbabwe".', 'max_length': 120}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional URL anchor. Leave blank to generate from the title.', 'max_length': 120, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'What this classification means.'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Step', 'max_length': 200}), 6: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Optional process steps (useful for Packaged / Assembled).', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Example', 'max_length': 300}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Concrete examples of this classification.', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Note'}), 10: ('wagtail.blocks.ListBlock', (9,), {'default': [], 'help_text': 'Limitations, distinctions, or extra guidance.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 2), ('anchor_slug', 3), ('definition', 4), ('steps', 6), ('examples', 8), ('notes', 10)]], {})}),
        ),
    ]
