# Generated by Django 6.1 on 2026-09-30 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productclassificationpage_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verification_source',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('staff', 'Simudza staff')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
