# Generated by Django 6.1 on 2026-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_sold_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, help_text='Optional label, e.g. "330 ml can".', max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='packaging',
            field=models.CharField(blank=True, help_text='e.g. "PET bottle", "Can".', max_length=200),
        ),
    ]
