# Generated by Django 6.1 on 2026-09-30 09:33

import businesses.videos
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productvariant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('url', models.URLField(max_length=500, validators=[businesses.videos.validate_youtube_url], verbose_name='YouTube link')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('demonstration', 'Product demonstration'), ('factory_tour', 'Factory tour'), ('manufacturing', 'Manufacturing process'), ('advertisement', 'Advertisement'), ('interview', 'Farmer / producer interview'), ('review', 'Product review'), ('other', 'Other')], default='other', max_length=30)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'verbose_name': 'product video',
                'verbose_name_plural': 'product videos',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
