# Generated by Django 6.1 on 2026-10-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_videos'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='productvariant_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('size_value__isnull', True), ('size_value__gt', 0), _connector='OR'), name='productvariant_size_value_positive'),
        ),
    ]
