# Generated by Django 6.1 on 2026-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_product_quality_gin_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
