# Generated by Django 6.1 on 2026-10-09 00:21

from django.db import migrations, models

LEVEL_MAP = {
    "verified_manufacturer": "simudza_verified",
    "simudza_checked": "simudza_verified",
    "verified_source": "source_verified",
}


def split_levels_and_lifecycle(apps, schema_editor):
    """Discontinued becomes a lifecycle status; its old level is unknown, so unverified."""
    Product = apps.get_model("products", "Product")
    Product.objects.filter(verification_level="discontinued").update(
        lifecycle_status="discontinued",
        verification_level="unverified",
    )
    for old, new in LEVEL_MAP.items():
        Product.objects.filter(verification_level=old).update(verification_level=new)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_verified_at_no_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued / withdrawn')], db_index=True, default='active', help_text='Discontinued keeps the page online with a notice but removes the product from search.', max_length=20),
        ),
        migrations.RunPython(split_levels_and_lifecycle, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='verification_level',
            field=models.CharField(choices=[('simudza_verified', 'Simudza Verified'), ('source_verified', 'Information source checked'), ('community_reported', 'Community reported — not verified by Simudza'), ('unverified', 'Not yet verified')], db_index=True, default='unverified', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='verification_reference',
            field=models.CharField(blank=True, help_text='Source name or URL when level is Information source checked.', max_length=300),
        ),
    ]
