# Generated by Django 6.1 on 2026-10-09 21:14

from django.db import migrations, models

OLD_TO_NEW = {
    "factory_tour": "manufacturing",
    "review": "testimonial",
    "interview": "other",
}


def remap_kinds(apps, schema_editor):
    ProductVideo = apps.get_model("products", "ProductVideo")
    for old, new in OLD_TO_NEW.items():
        ProductVideo.objects.filter(kind=old).update(kind=new)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_verification_levels_and_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='kind',
            field=models.CharField(choices=[('demonstration', 'Product demonstration'), ('service_demonstration', 'Service demonstration'), ('how_to', 'How-to and educational'), ('manufacturing', 'Manufacturing process'), ('testimonial', 'Customer testimonial'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.RunPython(remap_kinds, migrations.RunPython.noop),
    ]
